# Site
name: Arjun U Menon
description: 'This is where I jot down my learnings of Microsoft 365 and SharePoint Development.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'arjunumenon'
email: 'arjun.umenon@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag


# Author Settings
author: Arjun U Menon # add your name
author-img: Arjun.png # add your photo
about-author: Microsoft 365 developer who lives inside the cloud. # add description
social-twitter: arjunumenon # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: arjunumenon # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Arjun
      avatar: /assets/images/Arjun.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules,vendor]