# Site
name: Arjun U Menon
description: 'This is where I jot down my learnings of Microsoft 365 and SharePoint Development. Best practices about Microsft 365 development'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'arjunumenon'
email: 'arjun.umenon@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag


# Author Settings
author: Arjun U Menon # add your name
author-img: Arjun.png # add your photo
about-author: Microsoft 365 consultant. Living inside the cloud. # add description
social-twitter: arjunumenon #Twitter Handle
social-facebook: # Facebook handle
social-github: arjunumenon #  Github handle
social-linkedin: arjunumenon # Linkedin handle
social-email: arjun@a-um.me #  Email address

#Custom Configurations - Changed on runtime
sticky-char-trunc: 128 #Give the number of charachters to be truncated
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Arjun
      avatar: /assets/images/Arjun.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules,vendor]